namespace AICO.Domain.DTOs
{
    /// <summary>
    /// Comprehensive A/B test results
    /// </summary>
    public class AbTestResults
    {
        /// <summary>
        /// Test ID
        /// </summary>
        public Guid TestId { get; set; }

        /// <summary>
        /// Test name
        /// </summary>
        public string TestName { get; set; } = string.Empty;

        /// <summary>
        /// Test status
        /// </summary>
        public string Status { get; set; } = string.Empty;

        /// <summary>
        /// Test start date
        /// </summary>
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Test end date
        /// </summary>
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Control variant results
        /// </summary>
        public VariantResults ControlVariant { get; set; } = new();

        /// <summary>
        /// Test variant results
        /// </summary>
        public List<VariantResults> TestVariants { get; set; } = new();

        /// <summary>
        /// Overall test confidence level
        /// </summary>
        public decimal ConfidenceLevel { get; set; }

        /// <summary>
        /// Statistical significance
        /// </summary>
        public decimal StatisticalSignificance { get; set; }

        /// <summary>
        /// Whether results are statistically significant
        /// </summary>
        public bool IsSignificant { get; set; }

        /// <summary>
        /// Best performing variant ID
        /// </summary>
        public Guid? WinningVariantId { get; set; }

        /// <summary>
        /// Improvement percentage of winning variant
        /// </summary>
        public decimal ImprovementPercentage { get; set; }

        /// <summary>
        /// P-value of the test
        /// </summary>
        public decimal PValue { get; set; }

        /// <summary>
        /// Test power
        /// </summary>
        public decimal TestPower { get; set; }

        /// <summary>
        /// Total sample size
        /// </summary>
        public int TotalSampleSize { get; set; }

        /// <summary>
        /// Test duration in days
        /// </summary>
        public int DurationDays { get; set; }

        /// <summary>
        /// Revenue metrics if available
        /// </summary>
        public RevenueMetrics? RevenueMetrics { get; set; }

        /// <summary>
        /// Test recommendations
        /// </summary>
        public List<string> Recommendations { get; set; } = new();

        /// <summary>
        /// Results calculated timestamp
        /// </summary>
        public DateTime CalculatedAt { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// Results for a specific variant
    /// </summary>
    public class VariantResults
    {
        /// <summary>
        /// Variant ID
        /// </summary>
        public Guid VariantId { get; set; }

        /// <summary>
        /// Variant name
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Number of visitors
        /// </summary>
        public int Visitors { get; set; }

        /// <summary>
        /// Number of conversions
        /// </summary>
        public int Conversions { get; set; }

        /// <summary>
        /// Conversion rate
        /// </summary>
        public decimal ConversionRate { get; set; }

        /// <summary>
        /// Confidence interval lower bound
        /// </summary>
        public decimal ConfidenceIntervalLower { get; set; }

        /// <summary>
        /// Confidence interval upper bound
        /// </summary>
        public decimal ConfidenceIntervalUpper { get; set; }

        /// <summary>
        /// Improvement over control (null for control variant)
        /// </summary>
        public decimal? ImprovementPercentage { get; set; }

        /// <summary>
        /// Revenue generated by this variant
        /// </summary>
        public decimal Revenue { get; set; }

        /// <summary>
        /// Revenue per visitor
        /// </summary>
        public decimal RevenuePerVisitor { get; set; }

        /// <summary>
        /// Whether this is the control variant
        /// </summary>
        public bool IsControl { get; set; }
    }
}