namespace AICO.Domain.DTOs;

/// <summary>
/// Result model for MCP calculation on a specific variant
/// </summary>
public class MCPVariantResult
{
    /// <summary>
    /// Unique identifier for the variant
    /// </summary>
    public Guid VariantId { get; set; }

    /// <summary>
    /// Name or description of the variant
    /// </summary>
    public string VariantName { get; set; } = string.Empty;

    /// <summary>
    /// Calculated MCP value for this variant
    /// </summary>
    public decimal MCP { get; set; }

    /// <summary>
    /// Revenue per conversion for this variant
    /// </summary>
    public decimal RevenuePerConversion { get; set; }

    /// <summary>
    /// Total revenue generated by this variant
    /// </summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>
    /// Revenue for this variant (alias for TotalRevenue)
    /// </summary>
    public decimal Revenue { get; set; }

    /// <summary>
    /// Total number of conversions for this variant
    /// </summary>
    public int TotalConversions { get; set; }

    /// <summary>
    /// Conversion rate for this variant
    /// </summary>
    public decimal ConversionRate { get; set; }

    /// <summary>
    /// Currency code for monetary values
    /// </summary>
    public string Currency { get; set; } = "USD";

    /// <summary>
    /// Total number of visitors for this variant
    /// </summary>
    public int Visitors { get; set; }

    /// <summary>
    /// Revenue per visitor for this variant
    /// </summary>
    public decimal RevenuePerVisitor { get; set; }

    /// <summary>
    /// Whether this variant is the control group
    /// </summary>
    public bool IsControl { get; set; }

    /// <summary>
    /// Total cost associated with this variant
    /// </summary>
    public decimal Cost { get; set; }

    /// <summary>
    /// Number of conversions for this variant
    /// </summary>
    public int Conversions { get; set; }

    /// <summary>
    /// Timestamp when the calculation was performed
    /// </summary>
    public DateTime CalculatedAt { get; set; } = DateTime.UtcNow;
}