namespace AICO.Domain.DTOs
{
    /// <summary>
    /// Statistics for a single variant in an A/B test
    /// </summary>
    public class VariantStats
    {
        /// <summary>
        /// Number of visitors who saw this variant
        /// </summary>
        public int Visitors { get; set; }

        /// <summary>
        /// Number of conversions for this variant
        /// </summary>
        public int Conversions { get; set; }

        /// <summary>
        /// Total revenue generated by this variant
        /// </summary>
        public decimal Revenue { get; set; }

        /// <summary>
        /// Conversion rate (calculated property)
        /// </summary>
        public decimal ConversionRate => Visitors > 0 ? (decimal)Conversions / Visitors : 0;
    }
}