using System.ComponentModel.DataAnnotations;

namespace AICO.Domain.Entities
{
    public enum RecommendationStatus
    {
        Pending,
        InProgress,
        Implemented,
        Rejected,
        Archived
    }

    /// <summary>
    /// Represents a recommendation generated by the AI analysis system
    /// </summary>
    public class Recommendation : BaseEntity
    {
        /// <summary>
        /// ID of the website this recommendation is for
        /// </summary>
        public Guid WebsiteId { get; private set; }

        /// <summary>
        /// ID of the analysis result that generated this recommendation
        /// </summary>
        public Guid AnalysisResultId { get; private set; }

        /// <summary>
        /// Type of recommendation (e.g., SEO, Performance, UX)
        /// </summary>
        public string RecommendationType { get; private set; }

        /// <summary>
        /// Title of the recommendation
        /// </summary>
        public string Title { get; private set; }

        /// <summary>
        /// Detailed description of the recommendation
        /// </summary>
        public string Description { get; private set; }

        /// <summary>
        /// Priority of the recommendation (1-5, 1 being highest)
        /// </summary>
        public int Priority { get; private set; }

        /// <summary>
        /// Expected impact of implementing this recommendation
        /// </summary>
        public string? ExpectedImpact { get; private set; }

        /// <summary>
        /// Estimated effort required to implement (Low, Medium, High)
        /// </summary>
        public string? ImplementationEffort { get; private set; }

        /// <summary>
        /// Current status of the recommendation
        /// </summary>
        public RecommendationStatus Status { get; private set; }

        /// <summary>
        /// Date when the recommendation was generated
        /// </summary>
        [Required]
        public DateTime GeneratedAt { get; private set; }

        /// <summary>
        /// Date when the recommendation was implemented (if applicable)
        /// </summary>
        public DateTime? ImplementedAt { get; private set; }

        /// <summary>
        /// Additional metadata in JSON format
        /// </summary>
        public string? Metadata { get; private set; }

        // Navigation properties
        /// <summary>
        /// The website this recommendation belongs to
        /// </summary>
        public virtual Website? Website { get; private set; }

        /// <summary>
        /// The analysis result that generated this recommendation
        /// </summary>
        public virtual AnalysisResult? AnalysisResult { get; private set; }

        // Private constructor for EF Core
        private Recommendation()
        {
        }

        public void UpdateStatus(RecommendationStatus newStatus)
        {
            // Add any validation logic for status transitions if needed
            Status = newStatus;
        }

        public void MarkAsImplemented()
        {
            Status = RecommendationStatus.Implemented;
            ImplementedAt = DateTime.UtcNow;
        }

        // Overloaded static factory method for creating a recommendation with fewer parameters
        public static Recommendation Create(
            Guid analysisResultId,
            string title,
            string description,
            int priority,
            string recommendationType) // Changed category to recommendationType
        {
            if (analysisResultId == Guid.Empty)
                throw new ArgumentException("Analysis Result ID is required", nameof(analysisResultId));

            if (string.IsNullOrWhiteSpace(title))
                throw new ArgumentException("Title is required", nameof(title));

            if (string.IsNullOrWhiteSpace(description))
                throw new ArgumentException("Description is required", nameof(description));

            if (priority < 1 || priority > 5)
                throw new ArgumentException("Priority must be between 1 and 5", nameof(priority));

            return new Recommendation
            {
                AnalysisResultId = analysisResultId,
                RecommendationType = recommendationType ?? "General", // Changed category to recommendationType
                Title = title.Trim(),
                Description = description.Trim(),
                Priority = priority,
                ExpectedImpact = "Medium", // Default value
                ImplementationEffort = "Medium", // Default value
                Status = RecommendationStatus.Pending,
                GeneratedAt = DateTime.UtcNow
            };
        }

        // CreateImplemented remains the same name, updated to use Enum
        public static Recommendation CreateImplemented(
            Guid analysisResultId,
            string title,
            string description,
            int priority,
            string recommendationType,
            DateTime implementedAt)
        {
            if (analysisResultId == Guid.Empty)
                throw new ArgumentException("Analysis Result ID is required", nameof(analysisResultId));

            if (string.IsNullOrWhiteSpace(title))
                throw new ArgumentException("Title is required", nameof(title));

            if (string.IsNullOrWhiteSpace(description))
                throw new ArgumentException("Description is required", nameof(description));

            if (priority < 1 || priority > 5)
                throw new ArgumentException("Priority must be between 1 and 5", nameof(priority));

            return new Recommendation
            {
                AnalysisResultId = analysisResultId,
                RecommendationType = recommendationType ?? "General", // Changed category to recommendationType
                Title = title.Trim(),
                Description = description.Trim(),
                Priority = priority,
                Status = RecommendationStatus.Implemented,
                GeneratedAt = DateTime.UtcNow,
                ImplementedAt = implementedAt
            };
        }

        // Renamed from Create to CreateDetailed
        public static Recommendation CreateDetailed(
            Guid websiteId,
            Guid analysisResultId,
            string recommendationType,
            string title,
            string description,
            int priority,
            string? expectedImpact, // Made nullable
            string? implementationEffort, // Made nullable
            string? metadata = null) // Already nullable, but good to be explicit
        {
            if (websiteId == Guid.Empty)
                throw new ArgumentException("Website ID is required", nameof(websiteId));

            if (analysisResultId == Guid.Empty)
                throw new ArgumentException("Analysis Result ID is required", nameof(analysisResultId));

            if (string.IsNullOrWhiteSpace(recommendationType))
                throw new ArgumentException("Recommendation type is required", nameof(recommendationType));

            if (string.IsNullOrWhiteSpace(title))
                throw new ArgumentException("Title is required", nameof(title));

            if (string.IsNullOrWhiteSpace(description))
                throw new ArgumentException("Description is required", nameof(description));

            if (priority < 1 || priority > 5)
                throw new ArgumentException("Priority must be between 1 and 5", nameof(priority));

            // implementationEffort can be null now, so the IsNullOrWhiteSpace check is important
            if (string.IsNullOrWhiteSpace(implementationEffort))
            {
                // Decide on default behavior or throw, for now let's allow null to pass to property
            }
            else
            {
                var validEfforts = new[] { "Low", "Medium", "High" };
                if (!Array.Exists(validEfforts, effort => effort.Equals(implementationEffort, StringComparison.OrdinalIgnoreCase)))
                    throw new ArgumentException("Implementation effort must be Low, Medium, or High", nameof(implementationEffort));
            }

            return new Recommendation
            {
                Id = Guid.NewGuid(), // Ensure Id is set
                WebsiteId = websiteId,
                AnalysisResultId = analysisResultId,
                RecommendationType = recommendationType.Trim(),
                Title = title.Trim(),
                Description = description.Trim(),
                Priority = priority,
                ExpectedImpact = expectedImpact?.Trim(), // Remains the same, handles null
                ImplementationEffort = implementationEffort?.Trim(), // Add null conditional for Trim
                Status = RecommendationStatus.Pending, // Default status
                GeneratedAt = DateTime.UtcNow,
                Metadata = metadata
            };
        }

        public void UpdateTitle(string title)
        {
            if (string.IsNullOrWhiteSpace(title))
                throw new ArgumentException("Title is required", nameof(title));
            Title = title.Trim();
        }

        public void UpdateDescription(string description)
        {
            if (string.IsNullOrWhiteSpace(description))
                throw new ArgumentException("Description is required", nameof(description));
            Description = description.Trim();
        }

        public void UpdatePriority(int priority)
        {
            if (priority < 1 || priority > 5)
                throw new ArgumentException("Priority must be between 1 and 5", nameof(priority));
            Priority = priority;
        }

        public void UpdateRecommendationType(string newRecommendationType)
        {
            if (string.IsNullOrWhiteSpace(newRecommendationType))
                throw new ArgumentException("Recommendation type cannot be null or empty", nameof(newRecommendationType));
            RecommendationType = newRecommendationType.Trim();
            MarkAsUpdated();
        }

        public void MarkAsImplemented(DateTime? implementedDate = null)
        {
            Status = RecommendationStatus.Implemented;
            ImplementedAt = implementedDate ?? DateTime.UtcNow;
            MarkAsUpdated();
        }

        public void MarkAsPending()
        {
            Status = RecommendationStatus.Pending;
            ImplementedAt = null; // Clear implemented date when moving back to pending
            MarkAsUpdated();
        }

        public void MarkAsInProgress()
        {
            Status = RecommendationStatus.InProgress;
            ImplementedAt = null;
            MarkAsUpdated();
        }

        public void MarkAsRejected()
        {
            Status = RecommendationStatus.Rejected;
            ImplementedAt = null;
            MarkAsUpdated();
        }

        public void MarkAsArchived()
        {
            Status = RecommendationStatus.Archived;
            // Decide if ImplementedAt should be cleared or preserved for archived items
            // For now, let's clear it if not already implemented.
            if (Status != RecommendationStatus.Implemented) 
            {
                ImplementedAt = null;
            }
            MarkAsUpdated();
        }
    }
}