using System;
using System.ComponentModel.DataAnnotations;

namespace AICO.Domain.Entities
{
    /// <summary>
    /// Represents a recommendation generated by the AI analysis system
    /// </summary>
    public class Recommendation : BaseEntity
    {
        /// <summary>
        /// ID of the website this recommendation is for
        /// </summary>
        [Required]
        public Guid WebsiteId { get; private set; }

        /// <summary>
        /// ID of the analysis result that generated this recommendation
        /// </summary>
        [Required]
        public Guid AnalysisResultId { get; private set; }

        /// <summary>
        /// Type/category of the recommendation
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string RecommendationType { get; private set; }

        /// <summary>
        /// Title of the recommendation
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string Title { get; private set; }

        /// <summary>
        /// Detailed description of the recommendation
        /// </summary>
        [Required]
        [MaxLength(2000)]
        public string Description { get; private set; }

        /// <summary>
        /// Priority level of the recommendation (1-5, where 5 is highest)
        /// </summary>
        [Required]
        [Range(1, 5)]
        public int Priority { get; private set; }

        /// <summary>
        /// Expected impact of implementing this recommendation
        /// </summary>
        [MaxLength(500)]
        public string ExpectedImpact { get; private set; }

        /// <summary>
        /// Estimated effort required to implement (Low, Medium, High)
        /// </summary>
        [Required]
        [MaxLength(50)]
        public string ImplementationEffort { get; private set; }

        /// <summary>
        /// Current status of the recommendation
        /// </summary>
        [Required]
        [MaxLength(50)]
        public string Status { get; private set; }

        /// <summary>
        /// Date when the recommendation was generated
        /// </summary>
        [Required]
        public DateTime GeneratedAt { get; private set; }

        /// <summary>
        /// Date when the recommendation was implemented (if applicable)
        /// </summary>
        public DateTime? ImplementedAt { get; private set; }

        /// <summary>
        /// Additional metadata in JSON format
        /// </summary>
        public string Metadata { get; private set; }

        // Navigation properties
        /// <summary>
        /// The website this recommendation belongs to
        /// </summary>
        public virtual Website Website { get; private set; }

        /// <summary>
        /// The analysis result that generated this recommendation
        /// </summary>
        public virtual AnalysisResult AnalysisResult { get; private set; }

        // Private constructor for EF Core
        private Recommendation()
        {
        }

        // Static factory method for creating a new recommendation
        public static Recommendation Create(
            Guid websiteId,
            Guid analysisResultId,
            string recommendationType,
            string title,
            string description,
            int priority,
            string expectedImpact,
            string implementationEffort,
            string metadata = null)
        {
            if (websiteId == Guid.Empty)
                throw new ArgumentException("Website ID is required", nameof(websiteId));
            
            if (analysisResultId == Guid.Empty)
                throw new ArgumentException("Analysis Result ID is required", nameof(analysisResultId));
            
            if (string.IsNullOrWhiteSpace(recommendationType))
                throw new ArgumentException("Recommendation type is required", nameof(recommendationType));
            
            if (string.IsNullOrWhiteSpace(title))
                throw new ArgumentException("Title is required", nameof(title));
            
            if (string.IsNullOrWhiteSpace(description))
                throw new ArgumentException("Description is required", nameof(description));
            
            if (priority < 1 || priority > 5)
                throw new ArgumentException("Priority must be between 1 and 5", nameof(priority));
            
            if (string.IsNullOrWhiteSpace(implementationEffort))
                throw new ArgumentException("Implementation effort is required", nameof(implementationEffort));

            var validEfforts = new[] { "Low", "Medium", "High" };
            if (!Array.Exists(validEfforts, effort => effort.Equals(implementationEffort, StringComparison.OrdinalIgnoreCase)))
                throw new ArgumentException("Implementation effort must be Low, Medium, or High", nameof(implementationEffort));

            return new Recommendation
            {
                WebsiteId = websiteId,
                AnalysisResultId = analysisResultId,
                RecommendationType = recommendationType.Trim(),
                Title = title.Trim(),
                Description = description.Trim(),
                Priority = priority,
                ExpectedImpact = expectedImpact?.Trim(),
                ImplementationEffort = implementationEffort.Trim(),
                Status = "Pending",
                GeneratedAt = DateTime.UtcNow,
                Metadata = metadata
            };
        }

        // Method to mark recommendation as implemented
        internal void MarkAsImplemented()
        {
            if (Status == "Implemented")
                throw new InvalidOperationException("Recommendation is already marked as implemented");

            Status = "Implemented";
            ImplementedAt = DateTime.UtcNow;
        }

        // Method to update recommendation status
        internal void UpdateStatus(string newStatus)
        {
            if (string.IsNullOrWhiteSpace(newStatus))
                throw new ArgumentException("Status is required", nameof(newStatus));

            var validStatuses = new[] { "Pending", "In Progress", "Implemented", "Rejected", "Deferred" };
            if (!Array.Exists(validStatuses, status => status.Equals(newStatus, StringComparison.OrdinalIgnoreCase)))
                throw new ArgumentException("Invalid status value", nameof(newStatus));

            Status = newStatus;
            
            if (newStatus == "Implemented" && !ImplementedAt.HasValue)
            {
                ImplementedAt = DateTime.UtcNow;
            }
        }

        // Method to update priority
        internal void UpdatePriority(int newPriority)
        {
            if (newPriority < 1 || newPriority > 5)
                throw new ArgumentException("Priority must be between 1 and 5", nameof(newPriority));

            Priority = newPriority;
        }
    }
}